import type { IntakeSchema } from "@/lib/documents/intake/types";

export const employmentIntakeSchema: IntakeSchema = {
  documentType: "employment",
  steps: 3,
  fields: [
    {
      key: "company_name",
      type: "text",
      labelKey: "company_name",
      required: true,
      step: 1,
      placeholderKey: "company_name",
    },
    {
      key: "company_id",
      type: "text",
      labelKey: "company_id",
      required: true,
      step: 1,
      placeholderKey: "company_id",
    },
    {
      key: "employee_name",
      type: "text",
      labelKey: "employee_name",
      required: true,
      step: 1,
      placeholderKey: "employee_name",
    },
    {
      key: "employee_id",
      type: "text",
      labelKey: "employee_id",
      required: true,
      step: 1,
      placeholderKey: "employee_id",
    },
    {
      key: "employee_email",
      type: "email",
      labelKey: "employee_email",
      required: true,
      step: 1,
      placeholderKey: "employee_email",
    },
    {
      key: "role_title",
      type: "text",
      labelKey: "role_title",
      required: true,
      step: 2,
      placeholderKey: "role_title",
    },
    {
      key: "start_date",
      type: "date",
      labelKey: "start_date",
      required: true,
      step: 2,
    },
    {
      key: "salary_monthly_cop",
      type: "number",
      labelKey: "salary_monthly_cop",
      required: true,
      step: 2,
      placeholderKey: "salary_monthly_cop",
    },
    {
      key: "contract_type",
      type: "select",
      labelKey: "contract_type",
      required: true,
      step: 2,
      options: [
        { value: "indefinite", labelKey: "contract_indefinite" },
        { value: "fixed_term", labelKey: "contract_fixed" },
      ],
    },
    {
      key: "term_months",
      type: "number",
      labelKey: "term_months",
      required: false,
      step: 2,
      placeholderKey: "term_months",
      helpKey: "term_months",
    },
    {
      key: "non_compete",
      type: "select",
      labelKey: "non_compete",
      required: true,
      step: 3,
      options: [
        { value: "none", labelKey: "non_compete_none" },
        { value: "with_compensation", labelKey: "non_compete_compensated" },
      ],
    },
    {
      key: "jurisdiction_city",
      type: "text",
      labelKey: "jurisdiction_city",
      required: true,
      step: 3,
      placeholderKey: "jurisdiction_city",
    },
    {
      key: "company_representative",
      type: "text",
      labelKey: "company_representative",
      required: true,
      step: 3,
      placeholderKey: "company_representative",
    },
  ],
};
