import type { IntakeSchema } from "@/lib/documents/intake/types";

export const ipIntakeSchema: IntakeSchema = {
  documentType: "ip",
  steps: 2,
  fields: [
    {
      key: "company_name",
      type: "text",
      labelKey: "company_name",
      required: true,
      step: 1,
      placeholderKey: "company_name",
    },
    {
      key: "company_id",
      type: "text",
      labelKey: "company_id",
      required: true,
      step: 1,
      placeholderKey: "company_id",
    },
    {
      key: "assignor_name",
      type: "text",
      labelKey: "assignor_name",
      required: true,
      step: 1,
      placeholderKey: "assignor_name",
    },
    {
      key: "assignor_id",
      type: "text",
      labelKey: "assignor_id",
      required: true,
      step: 1,
      placeholderKey: "assignor_id",
    },
    {
      key: "assignor_email",
      type: "email",
      labelKey: "assignor_email",
      required: true,
      step: 1,
      placeholderKey: "assignor_email",
    },
    {
      key: "ip_description",
      type: "textarea",
      labelKey: "ip_description",
      required: true,
      step: 2,
      placeholderKey: "ip_description",
      helpKey: "ip_description",
    },
    {
      key: "assignment_scope",
      type: "select",
      labelKey: "assignment_scope",
      required: true,
      step: 2,
      options: [
        { value: "all_current_future", labelKey: "scope_all" },
        { value: "specified_only", labelKey: "scope_specified" },
      ],
    },
    {
      key: "consideration",
      type: "text",
      labelKey: "consideration",
      required: true,
      step: 2,
      placeholderKey: "consideration",
    },
    {
      key: "effective_date",
      type: "date",
      labelKey: "effective_date",
      required: true,
      step: 2,
    },
    {
      key: "jurisdiction_city",
      type: "text",
      labelKey: "jurisdiction_city",
      required: true,
      step: 2,
      placeholderKey: "jurisdiction_city",
    },
  ],
};
