import type { IntakeSchema } from "@/lib/documents/intake/types";

export const shareholdersIntakeSchema: IntakeSchema = {
  documentType: "shareholders",
  steps: 3,
  fields: [
    {
      key: "company_name",
      type: "text",
      labelKey: "company_name",
      required: true,
      step: 1,
      placeholderKey: "company_name",
    },
    {
      key: "company_id",
      type: "text",
      labelKey: "company_id",
      required: true,
      step: 1,
      placeholderKey: "company_id",
    },
    {
      key: "lead_investor_name",
      type: "text",
      labelKey: "lead_investor_name",
      required: true,
      step: 1,
      placeholderKey: "lead_investor_name",
    },
    {
      key: "lead_investor_id",
      type: "text",
      labelKey: "lead_investor_id",
      required: true,
      step: 1,
      placeholderKey: "lead_investor_id",
    },
    {
      key: "effective_date",
      type: "date",
      labelKey: "effective_date",
      required: true,
      step: 1,
    },
    {
      key: "drag_along_threshold_pct",
      type: "number",
      labelKey: "drag_along_threshold_pct",
      required: true,
      step: 2,
      placeholderKey: "drag_along_threshold_pct",
      helpKey: "drag_along_threshold_pct",
    },
    {
      key: "tag_along_enabled",
      type: "select",
      labelKey: "tag_along_enabled",
      required: true,
      step: 2,
      options: [
        { value: "yes", labelKey: "tag_along_yes" },
        { value: "no", labelKey: "tag_along_no" },
      ],
    },
    {
      key: "anti_dilution",
      type: "select",
      labelKey: "anti_dilution",
      required: true,
      step: 2,
      options: [
        { value: "none", labelKey: "anti_dilution_none" },
        { value: "broad_based", labelKey: "anti_dilution_broad" },
      ],
    },
    {
      key: "qualified_majority_pct",
      type: "number",
      labelKey: "qualified_majority_pct",
      required: true,
      step: 3,
      placeholderKey: "qualified_majority_pct",
      helpKey: "qualified_majority_pct",
    },
    {
      key: "dispute_resolution",
      type: "select",
      labelKey: "dispute_resolution",
      required: true,
      step: 3,
      options: [
        { value: "arbitration", labelKey: "dispute_arbitration" },
        { value: "courts", labelKey: "dispute_courts" },
      ],
    },
    {
      key: "jurisdiction_city",
      type: "text",
      labelKey: "jurisdiction_city",
      required: true,
      step: 3,
      placeholderKey: "jurisdiction_city",
    },
    {
      key: "company_representative",
      type: "text",
      labelKey: "company_representative",
      required: true,
      step: 3,
      placeholderKey: "company_representative",
    },
  ],
};
