import type { IntakeSchema } from "@/lib/documents/intake/types";

export const vestingIntakeSchema: IntakeSchema = {
  documentType: "vesting",
  steps: 3,
  fields: [
    {
      key: "company_name",
      type: "text",
      labelKey: "company_name",
      required: true,
      step: 1,
      placeholderKey: "company_name",
    },
    {
      key: "company_id",
      type: "text",
      labelKey: "company_id",
      required: true,
      step: 1,
      placeholderKey: "company_id",
    },
    {
      key: "founder_name",
      type: "text",
      labelKey: "founder_name",
      required: true,
      step: 1,
      placeholderKey: "founder_name",
    },
    {
      key: "founder_id",
      type: "text",
      labelKey: "founder_id",
      required: true,
      step: 1,
      placeholderKey: "founder_id",
    },
    {
      key: "founder_email",
      type: "email",
      labelKey: "founder_email",
      required: true,
      step: 1,
      placeholderKey: "founder_email",
    },
    {
      key: "shares_total",
      type: "number",
      labelKey: "shares_total",
      required: true,
      step: 2,
      placeholderKey: "shares_total",
    },
    {
      key: "vesting_months",
      type: "number",
      labelKey: "vesting_months",
      required: true,
      step: 2,
      placeholderKey: "vesting_months",
      helpKey: "vesting_months",
    },
    {
      key: "cliff_months",
      type: "number",
      labelKey: "cliff_months",
      required: true,
      step: 2,
      placeholderKey: "cliff_months",
      helpKey: "cliff_months",
    },
    {
      key: "vesting_start_date",
      type: "date",
      labelKey: "vesting_start_date",
      required: true,
      step: 2,
    },
    {
      key: "acceleration_type",
      type: "select",
      labelKey: "acceleration_type",
      required: true,
      step: 3,
      options: [
        { value: "none", labelKey: "acceleration_none" },
        { value: "single_trigger", labelKey: "acceleration_single" },
        { value: "double_trigger", labelKey: "acceleration_double" },
      ],
    },
    {
      key: "departure_treatment",
      type: "select",
      labelKey: "departure_treatment",
      required: true,
      step: 3,
      options: [
        { value: "forfeit", labelKey: "departure_forfeit" },
        { value: "partial", labelKey: "departure_partial" },
        { value: "negotiable", labelKey: "departure_negotiable" },
      ],
    },
    {
      key: "company_representative",
      type: "text",
      labelKey: "company_representative",
      required: true,
      step: 3,
      placeholderKey: "company_representative",
    },
    {
      key: "company_representative_title",
      type: "text",
      labelKey: "company_representative_title",
      required: true,
      step: 3,
      placeholderKey: "company_representative_title",
    },
    {
      key: "good_leaver_definition",
      type: "textarea",
      labelKey: "good_leaver_definition",
      required: false,
      step: 3,
      placeholderKey: "good_leaver_definition",
    },
    {
      key: "additional_terms",
      type: "textarea",
      labelKey: "additional_terms",
      required: false,
      step: 3,
      placeholderKey: "additional_terms",
    },
  ],
};
